name: Benchmark
on: [push, pull_request]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Install NASM
        uses: ilammy/setup-nasm@v1
      - name: Install x86_64-unknown-none target
        uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-unknown-none
      - name: Run Benchmarks
        run: cargo bench
        working-directory: ./charlotte_core