name: check
on: [push, pull_request]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install NASM
              uses: ilammy/setup-nasm@v1
            - name: Install x86_64-unknown-none target
              uses: dtolnay/rust-toolchain@stable
              with:
                target: x86_64-unknown-none
            - name: Cargo check
              run:
                cd charlotte_core && cargo check --target x86_64-unknown-none