name: Check
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Install NASM
        uses: ilammy/setup-nasm@v1
      - name: Install x86_64-unknown-none target
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-unknown-none
          cache-workspaces: ./charlotte_core
      - name: Check code
        run:
          cargo check --target ${{ matrix.target }} --manifest-path charlotte_core/Cargo.toml
      - name: Check code style
        run:
          cargo fmt --check --manifest-path charlotte_core/Cargo.toml