name: Check
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-none
          - aarch64-unknown-none
          - riscv64gc-unknown-none-elf
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Install NASM
        uses: ilammy/setup-nasm@v1
      - name: Install ${{ matrix.target }} target
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
          components: clippy, rustfmt
          cache: true
          cache-workspaces: ./charlotte_core
      - name: Check code
        run: |
          cargo clean
          cargo check --target ${{ matrix.target }} --manifest-path charlotte_core/Cargo.toml
      - name: Check code style with "fmt"
        run:
          cargo fmt --check --manifest-path charlotte_core/Cargo.toml
      - name: Check code style with "Clippy"
        run:
           cargo clippy --target ${{ matrix.target }} --manifest-path charlotte_core/Cargo.toml
