name: Clippy
on: [push, pull_request]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Install Clippy
        run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu clippy
      - name: Install NASM
        uses: ilammy/setup-nasm@v1
      - name: Install x86_64-unknown-none target
        uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-unknown-none
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings -Z build-std=core,alloc,std,panic_abort
        working-directory: ./charlotte_core
