name: Check Dependencies
on:
  workflow_call:

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Check for outdated dependencies
        run: cargo audit
