name: Security Audit
on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install NASM
        uses: ilammy/setup-nasm@v1
      - name: Install x86_64-unknown-none target
        uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-unknown-none
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run cargo audit
        run: cargo audit
        working-directory: ./charlotte_core
