name: Test code
on: [push, pull_request]

jobs:
  unit-test:
    uses: ./.github/workflows/tests/unit_tests.yml@main
    secrets: inherit
    with:
      toolchain: stable
  style-check:
    uses: ./.github/workflows/tests/style_check.yml@main
    secrets: inherit
  benchmark:
    needs: [unit-test, style-check]
    uses: ./.github/workflows/tests/benchmark.yml@main
    secrets: inherit
    with:
      toolchain: stable
